# General
base_url = "https://mofrim.codeberg.page"
compile_sass = false
minify_html = true
generate_feeds = true
generate_sitemap = true

# Taxonomies
taxonomies = [
    {name = "tags", feed = true, paginate_by = 10},
]

# Language
default_language = "en"

# [languages.en]
# build_search_index = true
# title = "mofrim.github.io"
# description = "mofrim's web-presence"

[languages.de]
generate_feeds = true # there will be a feed for French content
build_search_index = true
taxonomies = [
    {name = "tags", feed = true, paginate_by = 10},
]

[markdown]
render_emoji = true
external_links_target_blank = true
smart_punctuation = true
highlight_code = true
# highlight_theme = "gruvbox-dark"
highlight_theme = "dracula"

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[link_checker]
internal_level = "warn"

# Extra
[extra]
author = "mofrim"
favicon = "favicon.ico"
list_pages = false
list_posts = true
twitter_card = false
enable_search = true

## https://www.getzola.org/themes/even/
katex_enable = true
katex_auto_render = true

## Navigation
header_nav = [
  { url = "/", name_en = "/home", name_de = "/home" },
  { url = "/about", name_en = "/about", name_de = "/about" },
  { url = "/journal", name_en = "/journal", name_de = "/journal" },
  { url = "/blog", name_en = "/blog", name_de = "/blog" }
]
